# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 534)
        MainWindow.setStyleSheet("background-image: url(C:/Users/herme/Desktop/BlackJack UI/assets/images/download.jpeg)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.p_card_1 = QtWidgets.QLabel(self.centralwidget)
        self.p_card_1.setGeometry(QtCore.QRect(570, 340, 101, 141))
        self.p_card_1.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.p_card_1.setText("")
        self.p_card_1.setScaledContents(True)
        self.p_card_1.setObjectName("p_card_1")
        self.d_card_1 = QtWidgets.QLabel(self.centralwidget)
        self.d_card_1.setGeometry(QtCore.QRect(570, 10, 101, 141))
        self.d_card_1.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.d_card_1.setText("")
        self.d_card_1.setScaledContents(True)
        self.d_card_1.setObjectName("d_card_1")
        self.p_card_2 = QtWidgets.QLabel(self.centralwidget)
        self.p_card_2.setGeometry(QtCore.QRect(460, 340, 101, 141))
        self.p_card_2.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.p_card_2.setText("")
        self.p_card_2.setScaledContents(True)
        self.p_card_2.setObjectName("p_card_2")
        self.p_card_3 = QtWidgets.QLabel(self.centralwidget)
        self.p_card_3.setGeometry(QtCore.QRect(350, 340, 101, 141))
        self.p_card_3.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.p_card_3.setText("")
        self.p_card_3.setScaledContents(True)
        self.p_card_3.setObjectName("p_card_3")
        self.p_card_4 = QtWidgets.QLabel(self.centralwidget)
        self.p_card_4.setGeometry(QtCore.QRect(240, 340, 101, 141))
        self.p_card_4.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.p_card_4.setText("")
        self.p_card_4.setScaledContents(True)
        self.p_card_4.setObjectName("p_card_4")
        self.p_card_5 = QtWidgets.QLabel(self.centralwidget)
        self.p_card_5.setGeometry(QtCore.QRect(130, 340, 101, 141))
        self.p_card_5.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.p_card_5.setText("")
        self.p_card_5.setScaledContents(True)
        self.p_card_5.setObjectName("p_card_5")
        self.p_card_6 = QtWidgets.QLabel(self.centralwidget)
        self.p_card_6.setGeometry(QtCore.QRect(20, 340, 101, 141))
        self.p_card_6.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.p_card_6.setText("")
        self.p_card_6.setScaledContents(True)
        self.p_card_6.setObjectName("p_card_6")
        self.d_card_2 = QtWidgets.QLabel(self.centralwidget)
        self.d_card_2.setGeometry(QtCore.QRect(460, 10, 101, 141))
        self.d_card_2.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.d_card_2.setText("")
        self.d_card_2.setScaledContents(True)
        self.d_card_2.setObjectName("d_card_2")
        self.d_card_3 = QtWidgets.QLabel(self.centralwidget)
        self.d_card_3.setGeometry(QtCore.QRect(350, 10, 101, 141))
        self.d_card_3.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.d_card_3.setText("")
        self.d_card_3.setScaledContents(True)
        self.d_card_3.setObjectName("d_card_3")
        self.d_card_4 = QtWidgets.QLabel(self.centralwidget)
        self.d_card_4.setGeometry(QtCore.QRect(240, 10, 101, 141))
        self.d_card_4.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.d_card_4.setText("")
        self.d_card_4.setScaledContents(True)
        self.d_card_4.setObjectName("d_card_4")
        self.d_card_5 = QtWidgets.QLabel(self.centralwidget)
        self.d_card_5.setGeometry(QtCore.QRect(130, 10, 101, 141))
        self.d_card_5.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.d_card_5.setText("")
        self.d_card_5.setScaledContents(True)
        self.d_card_5.setObjectName("d_card_5")
        self.d_card_6 = QtWidgets.QLabel(self.centralwidget)
        self.d_card_6.setGeometry(QtCore.QRect(20, 10, 101, 141))
        self.d_card_6.setStyleSheet("border: 1px solid yellow;\n"
"border-radius: 5px")
        self.d_card_6.setText("")
        self.d_card_6.setScaledContents(True)
        self.d_card_6.setObjectName("d_card_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 160, 81, 31))
        self.label.setStyleSheet("font-size: 20px;\n"
"font-family: Georgia, serif;\n"
"color: white;\n"
"background-image: url(\"\");")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 81, 31))
        self.label_2.setStyleSheet("font-size: 20px;\n"
"font-family: Georgia, serif;\n"
"color: white;\n"
"background-image: url(\"\");")
        self.label_2.setObjectName("label_2")
        self.playerPoints = QtWidgets.QLabel(self.centralwidget)
        self.playerPoints.setGeometry(QtCore.QRect(120, 310, 47, 13))
        self.playerPoints.setStyleSheet("color: white;background-image: url(\"\");")
        self.playerPoints.setText("")
        self.playerPoints.setObjectName("playerPoints")
        self.dealerPoints = QtWidgets.QLabel(self.centralwidget)
        self.dealerPoints.setGeometry(QtCore.QRect(130, 170, 47, 13))
        self.dealerPoints.setStyleSheet("color: white;\n"
"opacity: 0%;background-image: url(\"\");")
        self.dealerPoints.setText("")
        self.dealerPoints.setObjectName("dealerPoints")
        self.moneyLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.moneyLabel.setGeometry(QtCore.QRect(790, 10, 101, 51))
        self.moneyLabel.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.moneyLabel.setStyleSheet("color: white;\n"
"border: 1px solid white;")
        self.moneyLabel.setObjectName("moneyLabel")
        self.betLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.betLabel.setGeometry(QtCore.QRect(250, 300, 64, 31))
        self.betLabel.setStyleSheet("color: white;")
        self.betLabel.setObjectName("betLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 300, 61, 31))
        self.label_3.setStyleSheet("font-size: 20px;\n"
"font-family: Georgia, serif;\n"
"color: white;background-image: url(\"\");")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(690, 260, 191, 221))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet("background-image: url(C:/Users/herme/Desktop/BlackJack UI/assets/images/black.jpg);\n"
"border: 2px outset #5A002C;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hitButton = QtWidgets.QPushButton(self.frame)
        self.hitButton.setEnabled(True)
        self.hitButton.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.hitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hitButton.setStyleSheet("background-color: #008000;\n"
"border-radius: 30px;\n"
"border: 2px solid grey;\n"
"border-style: outset;\n"
"background-image: url(\"\");\n"
"color: white;\n"
"font-size: 14px")
        self.hitButton.setObjectName("hitButton")
        self.standButton = QtWidgets.QPushButton(self.frame)
        self.standButton.setGeometry(QtCore.QRect(10, 80, 61, 61))
        self.standButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.standButton.setStyleSheet("background-color: #880808;\n"
"border-radius: 30px;\n"
"border: 2px solid grey;\n"
"border-style: outset;\n"
"background-image: url(\"\");\n"
"color: white;\n"
"font-size: 14px;")
        self.standButton.setObjectName("standButton")
        self.standButton_2 = QtWidgets.QPushButton(self.frame)
        self.standButton_2.setGeometry(QtCore.QRect(10, 150, 61, 61))
        self.standButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.standButton_2.setStyleSheet("background-color: blue;\n"
"border-radius: 30px;\n"
"border: 2px solid grey;\n"
"border-style: outset;\n"
"background-image: url(\"\");\n"
"color: white;\n"
"font-size: 14px;")
        self.standButton_2.setObjectName("standButton_2")
        self.chip50Button = QtWidgets.QPushButton(self.centralwidget)
        self.chip50Button.setGeometry(QtCore.QRect(300, 190, 91, 81))
        self.chip50Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chip50Button.setAutoFillBackground(False)
        self.chip50Button.setStyleSheet("border-radius: 40px;\n"
"\n"
"border-style: outset;\n"
"border-image: url(C:/Users/herme/Desktop/BlackJack UI/assets/images/chip50.png);\n"
"")
        self.chip50Button.setText("")
        self.chip50Button.setObjectName("chip50Button")
        self.chip10Button = QtWidgets.QPushButton(self.centralwidget)
        self.chip10Button.setGeometry(QtCore.QRect(190, 190, 91, 81))
        self.chip10Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chip10Button.setMouseTracking(True)
        self.chip10Button.setAutoFillBackground(False)
        self.chip10Button.setStyleSheet("border-radius: 40px;\n"
"\n"
"border-style: outset;\n"
"border-image: url(C:/Users/herme/Desktop/BlackJack UI/assets/images/chip10.png);\n"
"")
        self.chip10Button.setText("")
        self.chip10Button.setObjectName("chip10Button")
        self.chip100Button = QtWidgets.QPushButton(self.centralwidget)
        self.chip100Button.setGeometry(QtCore.QRect(410, 190, 91, 81))
        self.chip100Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chip100Button.setAutoFillBackground(False)
        self.chip100Button.setStyleSheet("border-radius: 40px;\n"
"border-image: url(C:/Users/herme/Desktop/BlackJack UI/assets/images/chip100.png);\n"
"")
        self.chip100Button.setText("")
        self.chip100Button.setObjectName("chip100Button")
        self.betButton = QtWidgets.QPushButton(self.centralwidget)
        self.betButton.setGeometry(QtCore.QRect(530, 210, 91, 41))
        self.betButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.betButton.setStyleSheet("color: white;")
        self.betButton.setObjectName("betButton")
        self.betLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.betLabel_2.setGeometry(QtCore.QRect(40, 250, 51, 16))
        self.betLabel_2.setStyleSheet("color: white;")
        self.betLabel_2.setText("")
        self.betLabel_2.setObjectName("betLabel_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(350, 180, 241, 111))
        self.widget.setStyleSheet("border: 3px groove grey;\n"
"background-image: url(\"\");\n"
"background-color: green;\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(130, 70, 75, 23))
        self.pushButton.setStyleSheet("background-color: white;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 181, 41))
        self.label_4.setStyleSheet("color: white;\n"
"border: 0px solid white;\n"
"font-size: 20px;\n"
"font-family: Georgia, serif;")
        self.label_4.setObjectName("label_4")
        self.frame.raise_()
        self.p_card_1.raise_()
        self.d_card_1.raise_()
        self.p_card_2.raise_()
        self.p_card_3.raise_()
        self.p_card_4.raise_()
        self.p_card_5.raise_()
        self.p_card_6.raise_()
        self.d_card_2.raise_()
        self.d_card_3.raise_()
        self.d_card_4.raise_()
        self.d_card_5.raise_()
        self.d_card_6.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.playerPoints.raise_()
        self.dealerPoints.raise_()
        self.moneyLabel.raise_()
        self.betLabel.raise_()
        self.label_3.raise_()
        self.chip50Button.raise_()
        self.chip10Button.raise_()
        self.chip100Button.raise_()
        self.betButton.raise_()
        self.betLabel_2.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Krupiye"))
        self.label_2.setText(_translate("MainWindow", "Oyuncu"))
        self.betLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Bahis:"))
        self.hitButton.setText(_translate("MainWindow", "Kart Çek"))
        self.standButton.setText(_translate("MainWindow", "Kal"))
        self.standButton_2.setText(_translate("MainWindow", "Teslim Ol"))
        self.betButton.setText(_translate("MainWindow", "Bahsi Onayla"))
        self.pushButton.setText(_translate("MainWindow", "Devam"))
        self.label_4.setText(_translate("MainWindow", "asdasdasdafasf"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
